### PR TITLE
Revert "Added support for CMake's config-based installation"

### LINKED ISSUE #29: platform macros and pre-built volk
To get the platform-specific function pointers, one of the macros (e.g. VK_USE_PLATFORM_WIN32_KHR) must be set before including vulkan.h. However, those macros need to be defined at volk build time as well. I totally didn't think of that when I made the cmake package config and the vcpkg port.  Doesn't this mean that volk will in practice always have to be built as part of a user's project? Automatically setting the right define doesn't seem to be an option: it'd work for win32, but it couldn't make the choice between xcb, xlib, wayland, etc.
Am I missing something here? How did that work with the earlier simple CMakeLists? It didn't set any defines either.

### PR DESCRIPTION
**Pull request by zeux**
Reverts zeux/volk#28

The core issue with the change is that volk really requires VK_USE_PLATFORM_XXX defines defined by the application externally, which makes it hard to provide pre-built binaries. While on non-Linux platforms there's an obvious (single) define, on Linux this depends on the windowing system the application wants to use.

Fixes #29

### CODE REVIEW

**Comment by zeux** [comment]
I'll keep this open for a bit just in case there are alternative ideas about resolving this that keep volk buildable without extraneous definitions.

**Comment by jweg** [comment]
I thought about it a bit more. Assuming proper defines in volk.h is fine, that is part of the user projects's environment, the only problem is volk.c doing compile-time logic.  Now whenever volk.c evaluates the defines / does conditional logic it's actually inside of (runtime) functions, so if only there was a way to do the respective checks at runtime... but that doesn't work, eventually it'll have to assign to the function pointers and their very existence depends on the defines, so I don't see a way to get out of compile-time.
That said, there is still a way to get volk installed and even into package managers like vcpkg: make it header-only, in a way. CMake could -- instead of a static library -- define an IMPORTED target that installs an include dir with both volk.h and volk.c. The user project must then #include volk.c in exactly one implementation file, after setting any desired defines either in code or in the build environment.
The existing static library could be kept as an additional option for when a user wants to add volk into his/her CMake build tree directly, but then the defines must be added to the volk target in CMake.
I've actually done that [in my fork](https://github.com/jweg/volk/commit/afa64efe3ae6dca74ffc0a85bc92bf38d2b48cea) and it works, of course, but it feels weird.

I started this because I really wanted my current project to be package-manager-managed and not deal with manual copying or updating git submodules this time, and this can make that work (again), but I don't know if it's worth so much weirdness in such a relatively simple library.

**Comment by zeux** [comment]
If a user project needs to include volk.c then it seems like there's no real value in this being a package TBH.

I think the real angle here is determining the platform defines automatically. It's something that came up before - you use volk, and then realize you can't use some swapchain extension. So you're forced to configure platform defines yourself. This is no worse than using Vulkan SDK but not great.

So if we *could* auto-detect the set of platform defines, this could make volk more user-friendly *and* packageable. Otherwise I feel like this is not worth it.

You mentioned earlier that it's impractical to enable all defines on Linux. Is there a subset that is practical to enable that's reasonable to start with? I don't know if we care about exotic things like Xrandr - is Wayland + X11 sufficient? Is it reasonable to expect that these headers are present on Linux systems or is that not the case?

**Comment by zeux** [comment]
Or maybe a reasonable start would be that in CMake setup, we *just* enable X11 and assume advanced users can use a non-packaged version.

**Comment by zeux** [comment]
Alternatively I wonder if we can do something similar to Windows and forward declare platform specific types to be able to enable Wayland/X11/etc support regardless of the presence of these headers.

**Comment by jweg** [comment]
Hi Arseny,

I couldn't find any time until now, but here are some more thoughts now.

I would advise against trying to detect the platforms in CMake; imo this must work perfectly if it's to be any good, and I don't think it has a chance to do that. The Vulkan platforms are a moving target and might even exceed CMake's concept of platforms (Nintendo, Fuchsia?). 
Pulling in everything and forward declaring things like with Windows is not a bad idea, but still requires maintenance and at least to me it's far from obvious what those types for all those platforms really are, the Vulkan headers don't even list the header files needed for them.

Also in general I really don't like the idea that the user must switch to a different usage pattern as soon as her usage of volk exceeds some "advanced" threshold. I want for volk to just work once it's in a project.

Instead, I propose to do something similar to AMD's vulkan-memory-allocator. They have a single header, but require that it's included exactly once with VMA_ALLOCATION defined which toggles the implementation definitions. 

- Solves the problem for now and for the future
- We could still provide a volk.c that does that special include 
- Not as strange looking as including a .c file (functionally equivalent, of course)
- With VMA doing it like that, not without precedence, not even in the Vulkan C++ space

I've made those changes in my fork.
Using volk there works in one of these ways:

- Build volk.c as part of the project's source:

    The build instructions in the readme are still valid.
    The caveats that existed before still apply, of course:
    - Must set platform defines as part of the build process somehow
    - Must get the volk and Vulkan include paths
    - Must link to dl on non-Windows platforms

    This still works just the same, so projects that already use volk in this way will continue working.
When using CMake, we can do a little better:

- CMake: Include the volk dir through add_subdirectory(...) and link to "volk".
    Then in one file do:

    #define VOLK_IMPLEMENTATION
    #include "volk.h"

    - Defines can now also be set in source code
    - Include paths are amended properly
    - Transivitive dependencies to Vulkan and dl are handled 

- CMake: Build volk separately with -DVOLK_INSTALL=ON and use it later with find_package(volk CONFIG).
    Then it's the same as the previous method.
    VOLK_INSTALL defaults to OFF so as to not pollute user projects with an additional install target.
    This also enables C++ package manager workflow. I personally find those very useful even for non-compiled libs -- I like the unified source of non-object-code data like include paths and dependencies.

I added examples of all three usage patterns in the form of Travis tests.
The only thing I dropped is the static library target; the approach doesn't really work as we saw and I suspect noone used it for that reason alone.

The only thing I haven't updated yet is the readme. I'd like to hear your opinion first.

I must say I wasn't sure I'd like these changes, but now that I've tried them I really do and I'd like volk to go that direction.
It keeps the user in full control and provides opt-in convenience without compromising that at all.

**Comment by zeux** [comment]
What's the difference between this and including volk.c into a translation unit of your choice? I don't like the fact that with this change, using volk as a CMake dependency becomes harder because you have to add source files to your project to compile it. I would like to make sure that existing users of volk, who are happy enough compiling volk.c (possibly while defining platform macros), stay happy with no changes on their side.

**Comment by zeux** [comment]
... oh, volk.c is still around (GitHub diff almost made it look like it's being removed by this change)

Is volk_impl.h meaningfully different from volk.c?

**Comment by jweg** [comment]
Oh, I was very careful to not break the normal way of including volk, so volk.c never left.
Really the only reason for volk_impl.h was that I thought it too weird to install a .c file in an include path, but it works, of course. Let's keep it simple, so I've moved the implementation back and included your idea to avoid the dependency cycle when not evaluating macros.
I've created a new pull request for the whole thing.

**Pull request closed without merging**
